# Generated by Django 3.2.7 on 2021-09-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_hash', models.CharField(max_length=100)),
                ('secretText', models.TextField()),
                ('createdAt', models.DateTimeField()),
                ('expiresAt', models.DateTimeField()),
                ('remainingViews', models.IntegerField()),
            ],
        ),
    ]
